GET http://localhost:5000/products

###
GET http://localhost:5000/products/3

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "cliener",
    "price": 452
}

###
PATCH  http://localhost:5000/products/7
Content-Type: application/json

{
    "name": "Pelembab wajah",
    "price": 34
}

###
DELETE  http://localhost:5000/products/5